// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package v1

import (
	"github.com/usememos/memos/server/profile"
	"testing"
)

// TestString_7164df2486 tests the String method of ActivityLevel
func TestString_7164df2486(t *testing.T) {
	// Test case 1: Check if the method returns the correct string
	activityLevel1 := profile.ActivityLevel("High")
	expectedOutput1 := "High"
	if activityLevel1.String() != expectedOutput1 {
		t.Errorf("Failed TestString_7164df2486: Expected %s but got %s", expectedOutput1, activityLevel1.String())
	} else {
		t.Logf("Success TestString_7164df2486: Expected %s and got %s", expectedOutput1, activityLevel1.String())
	}

	// Test case 2: Check if the method handles empty string correctly
	activityLevel2 := profile.ActivityLevel("")
	expectedOutput2 := ""
	if activityLevel2.String() != expectedOutput2 {
		t.Errorf("Failed TestString_7164df2486: Expected %s but got %s", expectedOutput2, activityLevel2.String())
	} else {
		t.Logf("Success TestString_7164df2486: Expected %s and got %s", expectedOutput2, activityLevel2.String())
	}
}
