// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package cron

import (
    "testing"
    "sync"
    "time"
)

// TestMustAdd_085a7dd2c6 is a test function for MustAdd method
func TestMustAdd_085a7dd2c6(t *testing.T) {

    // Creating a new Cron instance
    c := NewCron()

    // Defining a jobID and cronExpr for testing
    jobID := "testJob"
    cronExpr := "@every 1s"

    // Defining a simple function to run
    run := func() {
        t.Log("Job is running")
    }

    // Adding the job to the Cron instance
    c.MustAdd(jobID, cronExpr, run)

    // Checking if the job has been added successfully
    if _, ok := c.jobs[jobID]; !ok {
        t.Errorf("MustAdd failed, job %s was not added", jobID)
    }

    // Testing if the job runs successfully
    var wg sync.WaitGroup
    wg.Add(1)
    go func() {
        defer wg.Done()
        time.Sleep(2 * time.Second)
        if c.jobs[jobID].lastRun.IsZero() {
            t.Errorf("Job %s did not run", jobID)
        }
    }()
    wg.Wait()

    // Testing panic on adding a job with the same jobID
    defer func() {
        if r := recover(); r == nil {
            t.Errorf("MustAdd did not panic when adding a job with an existing jobID")
        }
    }()
    c.MustAdd(jobID, cronExpr, run)
}
