// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package cron

import (
	"testing"
	"time"
)

// TestNew_fe2948375e is a test function for the New() function in the cron package.
func TestNew_fe2948375e(t *testing.T) {
	cron := New()

	// Test case 1: Check if the cron instance is not nil after creation
	if cron == nil {
		t.Error("Failed to create a new cron instance")
	} else {
		t.Log("Successfully created a new cron instance")
	}

	// Test case 2: Check if the default interval is 1 minute
	if cron.interval != 1*time.Minute {
		t.Errorf("Default interval is not 1 minute, got %v", cron.interval)
	} else {
		t.Log("Default interval is 1 minute")
	}

	// Test case 3: Check if the default timezone is UTC
	if cron.timezone != time.UTC {
		t.Errorf("Default timezone is not UTC, got %v", cron.timezone)
	} else {
		t.Log("Default timezone is UTC")
	}

	// Test case 4: Check if the jobs map is initialized and empty
	if cron.jobs == nil {
		t.Error("Jobs map is not initialized")
	} else if len(cron.jobs) != 0 {
		t.Errorf("Jobs map is not empty, got %v", len(cron.jobs))
	} else {
		t.Log("Jobs map is initialized and empty")
	}
}
