// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package cron

import (
	"testing"
	"time"
)

// TestNewMoment_8575e75606 is a test case for the NewMoment function.
func TestNewMoment_8575e75606(t *testing.T) {
	// Test case 1: Testing with current time
	t1 := time.Now()
	m1 := NewMoment(t1)
	if m1.Minute != t1.Minute() || m1.Hour != t1.Hour() || m1.Day != t1.Day() || m1.Month != int(t1.Month()) || m1.DayOfWeek != int(t1.Weekday()) {
		t.Errorf("TestNewMoment_8575e75606 failed on current time, got: %v, want: %v.", m1, t1)
	} else {
		t.Log("TestNewMoment_8575e75606 passed on current time")
	}

	// Test case 2: Testing with a specific time
	t2 := time.Date(2022, 12, 31, 23, 59, 0, 0, time.UTC)
	m2 := NewMoment(t2)
	if m2.Minute != t2.Minute() || m2.Hour != t2.Hour() || m2.Day != t2.Day() || m2.Month != int(t2.Month()) || m2.DayOfWeek != int(t2.Weekday()) {
		t.Errorf("TestNewMoment_8575e75606 failed on specific time, got: %v, want: %v.", m2, t2)
	} else {
		t.Log("TestNewMoment_8575e75606 passed on specific time")
	}
}
