// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package cron

import (
	"testing"
)

// TestNewSchedule_2e9175244b is a test function for NewSchedule method
func TestNewSchedule_2e9175244b(t *testing.T) {

	// defining test cases
	testCases := []struct {
		name      string
		cronExpr  string
		wantError bool
	}{
		{
			name:      "Valid Cron Expression",
			cronExpr:  "*/15 0 1,15 * 1-5",
			wantError: false,
		},
		{
			name:      "Invalid Cron Expression - More than 5 segments",
			cronExpr:  "*/15 0 1,15 * 1-5 extra",
			wantError: true,
		},
		{
			name:      "Invalid Cron Expression - Less than 5 segments",
			cronExpr:  "*/15 0 1,15",
			wantError: true,
		},
		{
			name:      "Invalid Cron Expression - Invalid minute",
			cronExpr:  "60 0 1,15 * 1-5",
			wantError: true,
		},
	}

	// running test cases
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := NewSchedule(tc.cronExpr)
			if (err != nil) != tc.wantError {
				t.Errorf("NewSchedule() error = %v, wantError %v", err, tc.wantError)
				return
			}
			if err == nil {
				t.Logf("Success: %v", tc.name)
			}
		})
	}
}
