// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package cron

import (
    "testing"
    "sync"
)

type Cron struct {
    sync.Mutex
    jobs map[string]*job
}

type job struct {
    name string
}

func (c *Cron) RemoveAll() {
    c.Lock()
    defer c.Unlock()

    c.jobs = make(map[string]*job)
}

// TestRemoveAll_ebde6570ee tests the RemoveAll method of the Cron struct
func TestRemoveAll_ebde6570ee(t *testing.T) {
    // Initialize a new Cron instance with some jobs
    c := &Cron{
        jobs: map[string]*job{
            "job1": &job{name: "job1"},
            "job2": &job{name: "job2"},
            "job3": &job{name: "job3"},
        },
    }

    // Call the RemoveAll method
    c.RemoveAll()

    // Check if all jobs were removed
    if len(c.jobs) != 0 {
        t.Errorf("RemoveAll failed, expected 0 jobs, got %d", len(c.jobs))
    } else {
        t.Log("RemoveAll passed successfully, all jobs were removed")
    }

    // Try to remove jobs again from an already empty Cron instance
    c.RemoveAll()

    // Check if the jobs map is still empty
    if len(c.jobs) != 0 {
        t.Errorf("RemoveAll failed, expected 0 jobs, got %d", len(c.jobs))
    } else {
        t.Log("RemoveAll passed successfully, no jobs were found")
    }
}
