// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package cron

import (
	"sync"
	"testing"
)

type Cron struct {
	sync.Mutex
	jobs map[string]string
}

func (c *Cron) Remove(jobID string) {
	c.Lock()
	defer c.Unlock()

	delete(c.jobs, jobID)
}

func TestRemove_530b2079ac(t *testing.T) {
	cron := &Cron{
		jobs: map[string]string{
			"job1": "task1",
			"job2": "task2",
			"job3": "task3",
		},
	}

	// Test case 1: Remove an existing job
	cron.Remove("job1")
	if _, exists := cron.jobs["job1"]; exists {
		t.Error("Failed to remove job1")
	} else {
		t.Log("Successfully removed job1")
	}

	// Test case 2: Remove a non-existing job
	cron.Remove("job4")
	if _, exists := cron.jobs["job4"]; exists {
		t.Error("job4 should not exist")
	} else {
		t.Log("Successfully confirmed job4 does not exist")
	}
}
