// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package cron

import (
	"sync"
	"testing"
	"time"
)

type Cron struct {
	sync.RWMutex
	timezone *time.Location
}

func (c *Cron) SetTimezone(l *time.Location) {
	c.Lock()
	defer c.Unlock()

	c.timezone = l
}

func TestSetTimezone_be1ef08714(t *testing.T) {
	c := &Cron{}

	// Test case 1: Set timezone to UTC
	utc, _ := time.LoadLocation("UTC")
	c.SetTimezone(utc)
	if c.timezone != utc {
		t.Error("Failed to set timezone to UTC")
	} else {
		t.Log("Successfully set timezone to UTC")
	}

	// Test case 2: Set timezone to nil
	c.SetTimezone(nil)
	if c.timezone != nil {
		t.Error("Failed to set timezone to nil")
	} else {
		t.Log("Successfully set timezone to nil")
	}
}
