// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package cron

import (
	"sync"
	"testing"
	"time"
)

type Cron struct {
	sync.Mutex
	ticker *time.Ticker
}

func (c *Cron) Stop() {
	c.Lock()
	defer c.Unlock()
	if c.ticker != nil {
		c.ticker.Stop()
		c.ticker = nil
	}
}

// TestStop_857bb01e4c tests the Stop method of the Cron struct
func TestStop_857bb01e4c(t *testing.T) {
	c := &Cron{
		ticker: time.NewTicker(1 * time.Second),
	}

	// Test case 1: Stop a running ticker
	c.Stop()
	if c.ticker != nil {
		t.Error("Failed to stop the ticker")
	} else {
		t.Log("Successfully stopped the ticker")
	}

	// Test case 2: Stop an already stopped ticker
	c.Stop()
	if c.ticker != nil {
		t.Error("Ticker was not nil after calling Stop on an already stopped ticker")
	} else {
		t.Log("Successfully called Stop on an already stopped ticker")
	}
}
